package com.gill.jlox.tokens;

public enum TokenType {
    NUMBER,
    STRING,
    TRUE, FALSE,
    PLUS, MINUS, STAR, SLASH,
    BANG,
    EOF, BANG_EQUAL, EQUAL_EQUAL,
    NIL, LEFT_PAREN, RIGHT_PAREN,
    LEFT_BRACE, RIGHT_BRACE,
    COMMA, DOT, SEMICOLON,
    EQUAL, LESS, LESS_EQUAL, GREATER, GREATER_EQUAL,
    IDENTIFIER,
    AND, OR,
    CLASS, SUPER, THIS,
    FOR, WHILE,
    FUN, RETURN,
    IF, ELSE,
    VAR, PRINT, PERCENT, BREAK, PLUS_PLUS, MINUS_MINUS,
}